-- MySQL Script generated by MySQL Workbench
-- seg 14 fev 2022 23:58:14 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydatabase
-- -----------------------------------------------------
USE `mydatabase`;

-- -----------------------------------------------------
-- Table `mydatabase`.`tb_accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_accounts`;

CREATE TABLE `tb_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(150) NOT NULL,
  `second_name` varchar(150) DEFAULT NULL,
  `email` varchar(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE = InnoDB;